### ISSUE TITLE
前端项目启动后接口提示defined

### ISSUE THREAD

**Issue by alchu4n** [testnet0/testnet-vue3#2]
clone 后端项目 https://github.com/testnet0/testnet-java 使用IDEA启动项目
![image](https://github.com/user-attachments/assets/bc5a3e7d-77cc-4507-be68-bf52fca25b78)

clone前端项目https://github.com/testnet0/testnet-vue3 

使用 pnpm install 安装依赖
![image](https://github.com/user-attachments/assets/26b9a7c2-9a83-49cc-80a9-47170ee4c3ab)

项目根目录创建 .env.development 配置文件
```text
#后台接口父地址(必填)
VITE_GLOB_API_URL=/jeecgboot

# 跨域代理，您可以配置多个 ,请注意，没有换行符
VITE_PROXY = [["/jeecgboot","http://localhost:8080/jeecg-boot/"],["/upload","http://localhost:3300/upload"]]
#后台接口全路径地址(必填)
VITE_GLOB_DOMAIN_URL=http://localhost:8080/jeecg-boot/
```

执行命令启动 pnpm dev

![image](https://github.com/user-attachments/assets/3a51933e-4496-46c4-baac-f6c8a4c1d184)

项目启动后，接口为 http://localhost:3100/jeecgbootundefined/sys/randomImage/1629428467008?_t=1725758471680

**Comment by testnet0** [comment]
已修复
